name: Converting To PDF

on:
  push:
    branches: 
      - action

jobs:
  convert:
    name: Convert portfolio to pdf
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update
      run: sudo apt-get update
    - name: Install
      run: sudo apt-get install xvfb libfontconfig wkhtmltopdf
    - name: Convert
      env:
        XDG_RUNTIME_DIR: /home/runner/work/_temp/_runner_file_commands/set_env_dd9f3848-e163-432e-802e-aaaf220e2f92
      run: xvfb-run wkhtmltopdf https://google.com assets/google.pdf